### ISSUE TITLE
 "execution reverted" error in browser when buying NFT minted from fresh copy of repo

### ISSUE THREAD

**Issue by tobek** [ProjectOpenSea/opensea-creatures#68]
I'm getting the 'Oops, the Ethereum network rejected this transaction :( The OpenSea devs have been alerted, but this problem is typically due an item being locked or untransferrable. The exact error was "execution reverted..."' error banner when trying to buy a token minted with this repo on the OpenSea site.

All I did was check out the repo and run the following (putting my wallet and API keys in env variables):

```
yarn
DEPLOY_CREATURES=1 truffle deploy --network rinkeby
NFT_CONTRACT_ADDRESS=0xb52c917D402Ff760218E8c17FB696b7a6179e93c node scripts/mint.js
```

The token mints properly, I set up a sale, but can't buy it. Here's the token: https://testnets.opensea.io/assets/0xb52c917d402ff760218e8c17fb696b7a6179e93c/1

Deploying contract from a copy of the repo at commit d681edc41e8ce4490a00722ef95f7a51ca3192e2 (before update of `openzeppelin-solidity` from v2 to v4) works, but I'd rather use v4 contracts!

Pastebin with JS console from the browser: https://pastebin.com/XPByJtXw

**Comment by TheMaxKim** [comment]
Hey @tobek , it looks like the assets I created also are running into an issue. I went ahead and reverted the changes for now so other people don't run into the issue while I look more closely into the root cause. Thanks for pointing this out in the other PR!

**Comment by tobek** [comment]
Great, thanks for looking into it. Would be awesome if there was any technical documentation about how buying on OpenSea is implemented (what actual contract methods are called, details or at least mocks of the proxy registry, etc.) so that this kind of functionality could be tested for. If there are docs for stuff like this let us know!

**Comment by myleaningstuff** [comment]
I am still getting this error on the latest opensea rinkeby. The initial buying works (A sells to B) but then if B puts the token for sale, C can not buy it. See https://testnets.opensea.io/assets/0x1e8b549d0fce56577fe5ed262dae442ec4c5e493/2 for eg, its on sale but on buying an error "Oops, the Ethereum network rejected this transaction :( The OpenSea devs have been alerted, but this problem is typically due an item being locked or untransferrable. The exact error was "execution reverted..." is thrown.

**Comment by djpysu** [comment]
Putting a sale works fine but buying it not.

seaport.js?8b9d:3058 Failed atomic match with args:  (11) .... Array(0) Error: execution reverted

Something related to gas estimates? Can you help @TheMaxKim ?

**Comment by TheMaxKim** [comment]
Hey @djpysu , what version of the OpenZeppelin token contracts are currently being used in your contracts locally?

**Comment by djpysu** [comment]
Hey @TheMaxKim , I'm using     "@openzeppelin/contracts": "^3.4.1",

Both Creature and CreatureFactory with pragma solidity ^0.6.0;

**Comment by TheMaxKim** [comment]
Hey @djpysu , if you're inheriting from the OZ ERC721 class, that's most likely related to the reason this issue was originally opened.

The more up to date OZ contracts aren't correctly calling the appropriate overriden `isApprovedForAll` method in the method checked prior to transfers, `_isApprovedOrOwner`: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.4.0/contracts/token/ERC721/ERC721.sol#L295

I spoke with the OZ team and they'll have this fixed in the next release (it's already committed to master), or you can do something similar to what I did [here in this PR](https://github.com/ProjectOpenSea/opensea-creatures/pull/79) to override those methods that call `ERC721.isApprovedForAll`. Closing this issue for now.

**Comment by Striffly** [comment]
Is there a way to debug a transaction executed on opensea (like when buying a NFT) with `truffle debug` ? I cannot see a transaction ID in the console, this is the only thing I'm missing.

**Comment by keagster** [comment]
Hey Crew, Just updated the contract to new OZ and tested with old. Still having this issue. Does anyone have a fix for this? I followed @TheMaxKim suggestion but, does not appear to resolve the issue for me.

Still unable to transfer from after setting for sale.

**Comment by IAmKio** [comment]
Same issue here, deployed contracts this morning using Creatures / Creatures Factory repository. Updated OZ contracts to latest 4.x, all compiled fine etc. Listing item is fine, but cannot be bought. Other NFTs from other projects can be bought but mine cannot. 

@TheMaxKim please let me know if I can provide any further information to help solve this issue.

**Comment by dmytro-boiko-dev** [comment]
Same.

**Comment by Erwin2222** [comment]
I have this problem on looksrare.

**Comment by underway2014** [comment]
same problem

**Comment by rbngz** [comment]
same here

**Comment by gasparyanyur** [comment]
the same problem

**Comment by HRaf** [comment]
same problem here with tatum

**Comment by tczzz** [comment]
same problem
